### ISSUE TITLE
Running on Windows 10

### ISSUE THREAD

**Issue by twobob** [shanselman/babysmash#11]
Hi,

to get this to run on Windows 10 one must do some ninja parsing of the install directory to find the actual executable. Running from the start menu does not work.

Clearly this is a job for some post installation reg-exp with folder search (to do the ninja) and then maybe some in house co-ercing on your part to get a suitable startmenu icon magicked into life from this new info.

This first part I could do myself.  We use this app regularly with our tiny infants right thru to early years and have expounded its virtues evangelically to all of our parents since business began.

It would not be a tough step for a group such as ourselves (and in that I include all contrubutors to this project).

Comments?

Our dekstop icons work btw.

**Comment by DavidRieman** [comment]
I also have it running on Windows 10.  I do see the taskbar showing up still while BabySmash is running though, which is annoying.  I haven't tried the installer on Windows 10 yet though - Sounds like it leaves something to be desired?  IIRC, Scott never fully open-sourced the Installer part, so I'm not sure it's something I could look at anyway?  I think we'd need him to chime in at this point.

**Comment by shanselman** [comment]
Sorry, the installer is just ClickOnce. You can publish it yourself or not
use an installer at all, and run it from a folder. The "official" version
has to be Code Signed so that's why it's not 100% obvious.

I'll go through the PR and try to get http://babysmash.com updated in a few
weeks.

On Sat, Feb 20, 2016 at 8:22 PM, David Rieman <notifications@github.com>
wrote:

> I also have it running on Windows 10. I do see the taskbar showing up
> still while BabySmash is running though, which is annoying. I haven't tried
> the installer on Windows 10 yet though - Sounds like it leaves something to
> be desired? IIRC, Scott never fully open-sourced the Installer part, so I'm
> not sure it's something I could look at anyway? I think we'd need him to
> chime in at this point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shanselman/babysmash/issues/11#issuecomment-186737960>
> .
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by twobob** [comment]
I'm not sure that I properly described the original problem. Cardinal sin.

I believe it was the default Babysmash Icon (That is created in the Start Menu) "not firing" despite ostensibly pointing to the exe that is installed by the click-once in %LocalAppData%\Apps\2.0\foor\bar
(I kind of thought Mr Hanselman had done a post about it, but I may be wrong.)

Anyway: this can be circumvented by simply doing a search for the "real" exe and creating a shortcut to it manually and then sticking THAT on the start menu - that works.  

So this may be a shortcut format problem. I did find a post back in fab confirming the issue is "well known" and of course I can't find it now. When I turn it up or manage to get better test notes I will share.

Thanks very much for listening, we have a manual workaround for now.
If "Code signing" is indeed the issue, I don't recall any of those details from the time and fear that may be cross-purpose information.

**Comment by FormalDeterminism** [comment]
Setting ResizeMode = ResizeMode.NoResize on MainWindow seems to fix showing a couple of pixels of the taskbar, at least when running the executable. I did not test on clickonce.

**Comment by twobob** [comment]
nice on @FormalDeterminism . This is still a fave with the kids here.  good catch on that.

I was toying with a custom scancode registry injection to UTTERLY remove access to special keys, but there are only a few computers here with such buttons so.. not sure it is worth it.

For the record, we have never got it to run from the Start Menu in Windows 10, but then again all manner of apps exhibit "unique" features with respect to the new start bar xml setup so... Kludge works fine.
